INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (1, 'SAMSUNG', '갤럭시 S6', '갤럭시 S6', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (2, 'SAMSUNG', '갤럭시 S6 edge', '갤럭시 S6', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (3, 'SAMSUNG', '갤럭시 S6 edge+', '갤럭시 S6', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (4, 'SAMSUNG', '갤럭시 S6 active', '갤럭시 S6', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (5, 'SAMSUNG', '갤럭시 S7', '갤럭시 S7', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (6, 'SAMSUNG', '갤럭시 S7 edge', '갤럭시 S7', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (7, 'SAMSUNG', '갤럭시 S7 active', '갤럭시 S7', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (8, 'SAMSUNG', '갤럭시 S8', '갤럭시 S8', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (9, 'SAMSUNG', '갤럭시 S8+', '갤럭시 S8', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (10, 'SAMSUNG', '갤럭시 S8 active', '갤럭시 S8', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (11, 'SAMSUNG', '갤럭시 S9', '갤럭시 S9', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (12, 'SAMSUNG', '갤럭시 S9+', '갤럭시 S9', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (13, 'SAMSUNG', '갤럭시 S10', '갤럭시 S10', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (14, 'SAMSUNG', '갤럭시 S10+', '갤럭시 S10', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (15, 'SAMSUNG', '갤럭시 S10e', '갤럭시 S10', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (16, 'SAMSUNG', '갤럭시 S10 5G', '갤럭시 S10', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (17, 'SAMSUNG', '갤럭시 S10 Lite', '갤럭시 S10', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (18, 'SAMSUNG', '갤럭시 S20', '갤럭시 S20', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (19, 'SAMSUNG', '갤럭시 S20+', '갤럭시 S20', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (20, 'SAMSUNG', '갤럭시 S20 Ultra', '갤럭시 S20', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (21, 'SAMSUNG', '갤럭시 S20 FE', '갤럭시 S20', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (22, 'SAMSUNG', '갤럭시 S21', '갤럭시 S21', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (23, 'SAMSUNG', '갤럭시 S21+', '갤럭시 S21', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (24, 'SAMSUNG', '갤럭시 S21 Ultra', '갤럭시 S21', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (25, 'SAMSUNG', '갤럭시 S21 FE', '갤럭시 S21', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (26, 'SAMSUNG', '갤럭시 S22', '갤럭시 S22', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (27, 'SAMSUNG', '갤럭시 S22+', '갤럭시 S22', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (28, 'SAMSUNG', '갤럭시 S22 Ultra', '갤럭시 S22', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (29, 'SAMSUNG', '갤럭시 S23', '갤럭시 S23', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (30, 'SAMSUNG', '갤럭시 S23+', '갤럭시 S23', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (31, 'SAMSUNG', '갤럭시 S23 Ultra', '갤럭시 S23', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (32, 'SAMSUNG', '갤럭시 S23 FE', '갤럭시 S23', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (33, 'SAMSUNG', '갤럭시 S24', '갤럭시 S24', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (34, 'SAMSUNG', '갤럭시 S24+', '갤럭시 S24', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (35, 'SAMSUNG', '갤럭시 S24 Ultra', '갤럭시 S24', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (36, 'SAMSUNG', '갤럭시 S24 FE', '갤럭시 S24', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (37, 'SAMSUNG', '갤럭시 S25', '갤럭시 S25', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (38, 'SAMSUNG', '갤럭시 S25+', '갤럭시 S25', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (39, 'SAMSUNG', '갤럭시 S25 Edge', '갤럭시 S25', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (40, 'SAMSUNG', '갤럭시 S25 Ultra', '갤럭시 S25', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (41, 'SAMSUNG', '갤럭시 S25 FE', '갤럭시 S25', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (42, 'SAMSUNG', '갤럭시 Z 폴드', '갤럭시 Z 폴드', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (43, 'SAMSUNG', '갤럭시 Z 폴드2', '갤럭시 Z 폴드2', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (44, 'SAMSUNG', '갤럭시 Z 폴드3', '갤럭시 Z 폴드3', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (45, 'SAMSUNG', '갤럭시 Z 폴드4', '갤럭시 Z 폴드4', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (46, 'SAMSUNG', '갤럭시 Z 폴드5', '갤럭시 Z 폴드5', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (47, 'SAMSUNG', '갤럭시 Z 폴드6', '갤럭시 Z 폴드6', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (48, 'SAMSUNG', '갤럭시 Z 폴드 SE', '갤럭시 Z 폴드 SE', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (49, 'SAMSUNG', '갤럭시 Z 폴드7', '갤럭시 Z 폴드7', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (50, 'SAMSUNG', '갤럭시 Z 플립', '갤럭시 Z 플립', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (51, 'SAMSUNG', '갤럭시 Z 플립 5G', '갤럭시 Z 플립', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (52, 'SAMSUNG', '갤럭시 Z 플립2', '갤럭시 Z 플립2', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (53, 'SAMSUNG', '갤럭시 Z 플립3', '갤럭시 Z 플립3', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (54, 'SAMSUNG', '갤럭시 Z 플립4', '갤럭시 Z 플립4', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (55, 'SAMSUNG', '갤럭시 Z 플립5', '갤럭시 Z 플립5', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (56, 'SAMSUNG', '갤럭시 Z 플립6', '갤럭시 Z 플립6', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (57, 'SAMSUNG', '갤럭시 Z 플립7', '갤럭시 Z 플립7', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (58, 'SAMSUNG', '갤럭시 Z 플립7 FE', '갤럭시 Z 플립7', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (59, 'SAMSUNG', '갤럭시 Z 트라이플드', '갤럭시 Z 트라이플드', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (60, 'APPLE', '아이폰 5', '아이폰 5', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (61, 'APPLE', '아이폰 5c', '아이폰 5', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (62, 'APPLE', '아이폰 5s', '아이폰 5', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (63, 'APPLE', '아이폰 6', '아이폰 6', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (64, 'APPLE', '아이폰 6+', '아이폰 6', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (65, 'APPLE', '아이폰 6s', '아이폰 6', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (66, 'APPLE', '아이폰 6s+', '아이폰 6', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (67, 'APPLE', '아이폰 7', '아이폰 7', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (68, 'APPLE', '아이폰 7+', '아이폰 7', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (69, 'APPLE', '아이폰 8', '아이폰 8', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (70, 'APPLE', '아이폰 8+', '아이폰 8', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (71, 'APPLE', '아이폰 X', '아이폰 X', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (72, 'APPLE', '아이폰 XR', '아이폰 XR', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (73, 'APPLE', '아이폰 XS', '아이폰 XS', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (74, 'APPLE', '아이폰 XS Max', '아이폰 XS', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (75, 'APPLE', '아이폰 11', '아이폰 11', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (76, 'APPLE', '아이폰 11 Pro', '아이폰 11', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (77, 'APPLE', '아이폰 11 Pro Max', '아이폰 11', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (78, 'APPLE', '아이폰 12', '아이폰 12', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (79, 'APPLE', '아이폰 12 mini', '아이폰 12', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (80, 'APPLE', '아이폰 12 Pro', '아이폰 12', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (81, 'APPLE', '아이폰 12 Pro Max', '아이폰 12', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (82, 'APPLE', '아이폰 13', '아이폰 13', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (83, 'APPLE', '아이폰 13 mini', '아이폰 13', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (84, 'APPLE', '아이폰 13 Pro', '아이폰 13', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (85, 'APPLE', '아이폰 13 Pro Max', '아이폰 13', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (86, 'APPLE', '아이폰 14', '아이폰 14', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (87, 'APPLE', '아이폰 14+', '아이폰 14', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (88, 'APPLE', '아이폰 14 Pro', '아이폰 14', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (89, 'APPLE', '아이폰 14 Pro Max', '아이폰 14', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (90, 'APPLE', '아이폰 15', '아이폰 15', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (91, 'APPLE', '아이폰 15+', '아이폰 15', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (92, 'APPLE', '아이폰 15 Pro', '아이폰 15', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (93, 'APPLE', '아이폰 15 Pro Max', '아이폰 15', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (94, 'APPLE', '아이폰 16', '아이폰 16', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (95, 'APPLE', '아이폰 16+', '아이폰 16', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (96, 'APPLE', '아이폰 16 Pro', '아이폰 16', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (97, 'APPLE', '아이폰 16 Pro Max', '아이폰 16', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (98, 'APPLE', '아이폰 16e', '아이폰 16', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (99, 'APPLE', '아이폰 17', '아이폰 17', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (100, 'APPLE', '아이폰 Air', '아이폰 17', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (101, 'APPLE', '아이폰 17 Pro', '아이폰 17', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (102, 'APPLE', '아이폰 17 Pro Max', '아이폰 17', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (103, 'APPLE', '아이폰 SE', '아이폰 SE', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (104, 'APPLE', '아이폰 SE 2세대', '아이폰 SE 2세대', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (105, 'APPLE', '아이폰 SE 3세대', '아이폰 SE 3세대', 'PHONE');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (106, 'APPLE', '아이패드 1', '아이패드 1', 'TABLET');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (107, 'APPLE', '아이패드 2', '아이패드 2', 'TABLET');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (108, 'APPLE', '아이패드 3세대', '아이패드 3세대', 'TABLET');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (109, 'APPLE', '아이패드 4세대', '아이패드 4세대', 'TABLET');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (110, 'APPLE', '아이패드 5세대', '아이패드 5세대', 'TABLET');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (111, 'APPLE', '아이패드 6세대', '아이패드 6세대', 'TABLET');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (112, 'APPLE', '아이패드 7세대', '아이패드 7세대', 'TABLET');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (113, 'APPLE', '아이패드 8세대', '아이패드 8세대', 'TABLET');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (114, 'APPLE', '아이패드 9세대', '아이패드 9세대', 'TABLET');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (115, 'APPLE', '아이패드 10세대', '아이패드 10세대', 'TABLET');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (116, 'APPLE', '아이패드 A16', '아이패드 A16', 'TABLET');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (117, 'APPLE', '아이패드 mini', '아이패드 mini', 'TABLET');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (118, 'APPLE', '아이패드 mini2', '아이패드 mini2', 'TABLET');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (119, 'APPLE', '아이패드 mini3', '아이패드 mini3', 'TABLET');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (120, 'APPLE', '아이패드 mini4', '아이패드 mini4', 'TABLET');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (121, 'APPLE', '아이패드 mini 5세대', '아이패드 mini 5세대', 'TABLET');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (122, 'APPLE', '아이패드 mini 6세대', '아이패드 mini 6세대', 'TABLET');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (123, 'APPLE', '아이패드 mini A17 Pro', '아이패드 mini A17 Pro', 'TABLET');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (124, 'APPLE', '아이패드 Air', '아이패드 Air', 'TABLET');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (125, 'APPLE', '아이패드 Air2', '아이패드 Air2', 'TABLET');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (126, 'APPLE', '아이패드 Air 3세대', '아이패드 Air 3세대', 'TABLET');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (127, 'APPLE', '아이패드 Air 4세대', '아이패드 Air 4세대', 'TABLET');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (128, 'APPLE', '아이패드 Air 5세대', '아이패드 Air 5세대', 'TABLET');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (129, 'APPLE', '아이패드 Air 11 (M2)', '아이패드 Air 11 (M2)', 'TABLET');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (130, 'APPLE', '아이패드 Air 13 (M2)', '아이패드 Air 13 (M2)', 'TABLET');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (131, 'APPLE', '아이패드 Air 11 (M3)', '아이패드 Air 11 (M3)', 'TABLET');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (132, 'APPLE', '아이패드 Air 13 (M3)', '아이패드 Air 13 (M3)', 'TABLET');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (133, 'APPLE', '아이패드 Pro 9.7', '아이패드 Pro 9.7', 'TABLET');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (134, 'APPLE', '아이패드 Pro 10.5', '아이패드 Pro 10.5', 'TABLET');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (135, 'APPLE', '아이패드 Pro 11', '아이패드 Pro 11', 'TABLET');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (136, 'APPLE', '아이패드 Pro 11 2세대', '아이패드 Pro 11 2세대', 'TABLET');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (137, 'APPLE', '아이패드 Pro 11 3세대', '아이패드 Pro 11 3세대', 'TABLET');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (138, 'APPLE', '아이패드 Pro 11 4세대', '아이패드 Pro 11 4세대', 'TABLET');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (139, 'APPLE', '아이패드 Pro 12.9', '아이패드 Pro 12.9', 'TABLET');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (140, 'APPLE', '아이패드 Pro 12.9 2세대', '아이패드 Pro 12.9 2세대', 'TABLET');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (141, 'APPLE', '아이패드 Pro 12.9 3세대', '아이패드 Pro 12.9 3세대', 'TABLET');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (142, 'APPLE', '아이패드 Pro 12.9 4세대', '아이패드 Pro 12.9 4세대', 'TABLET');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (143, 'APPLE', '아이패드 Pro 12.9 5세대', '아이패드 Pro 12.9 5세대', 'TABLET');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (144, 'APPLE', '아이패드 Pro 12.9 6세대', '아이패드 Pro 12.9 6세대', 'TABLET');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (145, 'APPLE', '아이패드 Pro 11 (M4)', '아이패드 Pro 11', 'TABLET');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (146, 'APPLE', '아이패드 Pro 13 (M4)', '아이패드 Pro 13', 'TABLET');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (147, 'APPLE', '아이패드 Pro 11 (M5)', '아이패드 Pro 11', 'TABLET');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (148, 'APPLE', '아이패드 Pro 13 (M5)', '아이패드 Pro 13', 'TABLET');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (149, 'APPLE', '애플워치 1', '애플워치 1', 'WATCH');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (150, 'APPLE', '애플워치 2', '애플워치 2', 'WATCH');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (151, 'APPLE', '애플워치 3', '애플워치 3', 'WATCH');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (152, 'APPLE', '애플워치 4', '애플워치 4', 'WATCH');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (153, 'APPLE', '애플워치 5', '애플워치 5', 'WATCH');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (154, 'APPLE', '애플워치 6', '애플워치 6', 'WATCH');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (155, 'APPLE', '애플워치 7', '애플워치 7', 'WATCH');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (156, 'APPLE', '애플워치 8', '애플워치 8', 'WATCH');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (157, 'APPLE', '애플워치 9', '애플워치 9', 'WATCH');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (158, 'APPLE', '애플워치 10', '애플워치 10', 'WATCH');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (159, 'APPLE', '애플워치 11', '애플워치 11', 'WATCH');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (160, 'APPLE', '애플워치 SE', '애플워치 SE', 'WATCH');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (161, 'APPLE', '애플워치 SE 2', '애플워치 SE 2', 'WATCH');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (162, 'APPLE', '애플워치 SE 3', '애플워치 SE 3', 'WATCH');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (163, 'APPLE', '애플워치 Ultra', '애플워치 Ultra', 'WATCH');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (164, 'APPLE', '애플워치 Ultra 2', '애플워치 Ultra 2', 'WATCH');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (165, 'APPLE', '애플워치 Ultra 3', '애플워치 Ultra 3', 'WATCH');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (166, 'APPLE', '에어팟 1세대', '에어팟 1세대', 'ACCESSORY');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (167, 'APPLE', '에어팟 2세대', '에어팟 2세대', 'ACCESSORY');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (168, 'APPLE', '에어팟 3세대', '에어팟 3세대', 'ACCESSORY');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (169, 'APPLE', '에어팟 4세대', '에어팟 4세대', 'ACCESSORY');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (170, 'APPLE', '에어팟 Pro', '에어팟 Pro', 'ACCESSORY');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (171, 'APPLE', '에어팟 Pro 2', '에어팟 Pro 2', 'ACCESSORY');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (172, 'APPLE', '에어팟 Pro 3', '에어팟 Pro 3', 'ACCESSORY');
INSERT INTO devices (model_id, manufacturer, model, series, category) VALUES (173, 'APPLE', '에어팟 Max', '에어팟 Max', 'ACCESSORY');